package Ishimura.uade.IshimuraCollectibles.exceptions;

public enum ErrorCode {
    CATEGORY_ALREADY_EXISTS,
    CATEGORY_NOT_FOUND,
    VALIDATION_ERROR,
    AUTH_FORBIDDEN,
    AUTH_UNAUTHORIZED,
    AUTH_NOT_FOUND,
    LINE_ALREADY_EXISTS,
    INVALID_DOMAIN_STATE,
    DATA_INTEGRITY_VIOLATION,
    BRAND_NOT_FOUND,
    LINE_NOT_FOUND,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    ORDER_NOT_FOUND,
    IMAGE_NOT_FOUND,
    COLLECTIBLE_NOT_FOUND,
    CATALOG_ITEM_NOT_FOUND,
    PROMOTION_CONFLICT
    , COLLECTIBLE_ALREADY_EXISTS
    , WISHLIST_ITEM_ALREADY_EXISTS
}
